# Generated by Django 2.2 on 2021-09-11 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_auto_20210902_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=60)),
                ('model', models.CharField(default='', max_length=60)),
                ('VIN', models.CharField(default='', max_length=50)),
                ('purchaseDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastServiceDate', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='clients.Client')),
            ],
        ),
    ]
