# Generated by Django 2.2 on 2021-09-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='lastServiceDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchaseDate',
            field=models.DateTimeField(),
        ),
    ]
